# Generated by Django 4.2 on 2024-09-27 13:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_remove_blogmodel_views_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='ProfileOfUser',
        ),
    ]
