# Generated by Django 4.2 on 2024-09-27 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_follow_delete_likemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='Follower',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='Following',
            new_name='following',
        ),
    ]
